[project]
name = "voice-assistant"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "anthropic",
    "faster-whisper",
    "pyaudio",
    "RPi.GPIO",
    "adafruit-blinka",
    "adafruit-circuitpython-rgb-display",
    "Pillow",
    "sparkfun-qwiic-button",
    "sparkfun-qwiic-led-stick",
]
